### ISSUE TITLE
Loading status on Create

### ISSUE THREAD

**Issue by LeAlencar** [LeAlencar/relay-frontend#13]
I'm using Formik for creating the user, but the creation process is so fast that I can't show anything to the user realize that the creation was over. I was thinking on adding a little spin circle to the button and a little delay(3s). How?
![image](https://user-images.githubusercontent.com/52898510/177624384-7e82294a-5fc3-4855-850a-cc274635f6be.png)

**Comment by ddanielsantos** [comment]
add the spinner while the request to the server is being processed and use [this](https://www.browserstack.com/guide/how-to-perform-network-throttling-in-chrome) on your development environment to simulate the production one

**Comment by LeAlencar** [comment]
Thanks for the advice @ddanielsantos.
